services:
  nordvpn:
    build:
      context: .
      dockerfile: Dockerfile-nordvpn
    cap_add:
    - NET_ADMIN
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=0
    environment:
      NORDVPN_TOKEN: "<add access token here>"
    ports:
      - 8080:8080
    restart: unless-stopped
    healthcheck:
      test: /connect.sh
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 3s
  qbitorrent:
    build:
      context: .
      dockerfile: Dockerfile-qbitorrent
    network_mode: service:nordvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbitorrent-data:/config
      - C:\Downloads:/downloads
    restart: unless-stopped
    depends_on:
      nordvpn:
        condition: service_healthy
        restart: true

volumes:
  qbitorrent-data:

